name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Compile the program
      run: make
    - name: Upload the compiled binary
      uses: actions/upload-artifact@v4
      with:
          name: hello-binary
          path: ./main  

    - name: Run the program
      run: ./main
