name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Compile the program
      run: make
    - name: Upload artifact to JFrog Artifactory
      run: |
          curl -u ${{ secrets.JFROG_USER }}:${{ secrets.JFROG_PASSWORD }} \
            -T ./main "https://192.168.27.95/artifactory/example-repo-local/" 
            
