name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Compile the program
      run: make
    - name: Upload artifact to JFrog Artifactory
      run: |
          curl -u ${{ secrets.JFROG_USER }}:${{ secrets.JFROG_PASSWORD }} \
            -T ./main "http://127.0.0.1:8082/ui/repos/tree/General/my-repo" 

    - name: Run the program
      run: ./main
