name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Compile the program
      run: make
    #- name: Upload artifact to JFrog Artifactory
    #  run: |
    #     curl -u ${{ secrets.JFROG_USER }}:${{ secrets.JFROG_PASSWORD }} \
    #        -T ./main "https://192.168.27.95/artifactory/example-repo-local/" 
    - name: Set up JFrog CLI (without sudo)
      run: |
        curl -fL https://install-cli.jfrog.io | sh
        mkdir -p $HOME/.jfrog/bin
        mv jf $HOME/.jfrog/bin/
        echo "$HOME/.jfrog/bin" >> $GITHUB_PATH

    - name: Upload artifact to JFrog Artifactory
      run: |
        jfrog rt u "./main" "example-repo-local/"
            
