name: C/C++ CI

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Compile the program
      run: make
    - name: Upload artifact to JFrog Artifactory
      run: |
          curl -u ${{ secrets.JFROG_USER }}:${{ secrets.JFROG_PASSWORD }} \
            -T ./main "http://127.0.0.1:8082/artifactory/my-repo/" 

    - name: Run the program
      run: ./main
