name: jf-test

on:
   push:
    branches: [ "main" ]
  #workflow_dispatch:

jobs:
  create_zip_and_upload:

    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a sample file
      run: |
        echo "This is a sample file content" > sample-file.txt

    - name: Zip the file
      run: |
        zip sample-file.zip sample-file.txt

    - name: JF Debug
      run: |
         jf c show
         jf rt ping --server-id=artifactory-server

    - name: Upload to JFrog Artifactory
      run: |
        jf rt upload "sample-file.zip" "example-repo-local/sample-file.zip" --server-id=artifactory-server --insecure-tls

